[project]
name = "einsum-playground"
version = "0.1.0"
description = "Playground to explore einsum in pytorch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["torch>=2.5.1"]

[dependency-groups]
dev = ["ipykernel>=6.29.5"]
